language: csharp
solution: SokoGrump.sln
install:
  - wget https://raw.githubusercontent.com/hmlendea/deployment-scripts/master/monogame/install-monogame.sh -O monogame-install.sh
  - bash monogame-install.sh 3.6
script:
  - msbuild
